### ISSUE TITLE
Qgis 3

### ISSUE THREAD

**Issue by pekouille** [lmotta/imagefootprint_plugin#1]
Hi,

First of all, thank you for this excellent plugin which we use a lot in our office ! 
I tried to use it today with Qgis 3.4, but I have seen 2 problems : 
- The catalog's style is not transparent anymore
- The actions (show hide image, etc.) are not implemented in the catalog's data

another thing is that unfortunately, we can't use our old 2.18 catalogs in 3.4 because the old actions don't work anymore and lead to pythons errors.
Would it be possible for you to rewrite the actions with qgis 3.4 compatibility ?
Hope this will help you to solve the Qgis 3 portability issues, and thanks again for your hardwork !
Laurent Wilket

**Comment by lmotta** [comment]
Laurent,

Please update the 'IBAMA processing' plugin.
The footprint algorithm was updated.
